### ISSUE TITLE
Unable to run the application

### ISSUE THREAD

**Issue by flik** [mashingver/gallery#1]
This is error log:

[autoindex:error] [pid 27803] [client 119.160.66.115:65053] AH01276: Cannot serve directory /home/flik/www/gallery/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive

**Comment by mashingver** [comment]
flik, to run this gallery-app you should do the following:

- open /gallery/gemfile and delete three lines at the very bottom:
 group :production do
  gem 'pg'
end

- via terminal go to /gallery folder and run commands:
    1. bundle install
    2. bin/rake db:create
    3. bin/rake db:migrate
    4. rails server

- go to browser and write: localhost:3000   - you will get to main page

p.s. you should have Ruby and Ruby on Rails installed

2015-03-15 14:46 GMT+02:00 Mohammad Ashfaq <notifications@github.com>:

**Comment by flik** [comment]
@mashingver Let me check again.
